name: labproyecto2025
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  dartz: ^0.10.1
  get_it: ^7.6.7
  flutter_bloc: ^8.1.5
  hive : ^2.2.3
  hive_flutter: ^1.1.0  
  material_symbols_icons: ^4.2873.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
